### ISSUE TITLE
You can't pipe bashisms to `sh`

### ISSUE THREAD

**Issue by RichardBronosky** [aaronkjones/rpi-k8s-node-prep#1]
From your README:

    curl -sL https://raw.githubusercontent.com/aaronkjones/rpi-k8s-node-prep/master/prep.sh | sudo sh

but you use `[[` in your script (and have a `#!/bin/bash`)

In the least, it should be piping to `bash`. But really, you shouldn't do that unless everything in the entire script is wrapped in function definitions and the `main` function is called at the very end to ensure that none of it runs until and unless all of it is downloaded.

For example, see the very end of the file at https://get.docker.com/ All the "actions" are in functions. The begining of the file has a bunch of "bare" code in the top scope, but it is just defining variables. Nothing gets executed until `do_install`.

**Comment by aaronkjones** [comment]
:thumbsup:
Thanks for the feedback. You are right, despite it being a very short script (~100 lines) it should be wrapped in a function to avoid partial execution on connection drop. 

Fixed in e069abc0889ff9adbedeced7ef72599d6d342360
