### ISSUE TITLE
uname -a does not show raspbian

### ISSUE THREAD

**Issue by RichardBronosky** [aaronkjones/rpi-k8s-node-prep#2]
https://github.com/aaronkjones/rpi-k8s-node-prep/blob/master/prep.sh#L14

However...
```
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.14.50-v7+ #1122 SMP Tue Jun 19 12:26:26 BST 2018 armv7l GNU/Linux

pi@raspberrypi:~ $ cat /etc/os-release | grep raspbian;
ID=raspbian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

pi@raspberrypi:~ $ echo "exit code zero would mean success-> $?"
exit code zero would mean success-> 0
```

Running your script with `#!/bin/bash -x` shows:
```
+ uname -a
+ grep hypriot
+ uname -a
+ grep raspbian
+ [[ '' == \r\a\s\p\b\i\a\n ]]
+ [[ '' == \h\y\p\r\i\o\t ]]
+ echo 'OS type not known'
OS type not known
+ exit 1
```

**Comment by aaronkjones** [comment]
This is because the second string in `uname -a` is the hostname it seems, which by default is raspbian I guess.

Good catch.

**Comment by aaronkjones** [comment]
`lsb_release -si` is more reliable

**Comment by aaronkjones** [comment]
Fixed in 89174a0fdbc07732c00fb2eda4db3d680dafc511

I do not have Hypriot available to check what `lsb_release -si` returns. Will update when I do.

**Comment by RichardBronosky** [comment]
> `lsb_release -si` is more reliable

Agreed! That's what I normally use (and meant to suggest). Make sure you `grep -iq`.

**Comment by RichardBronosky** [comment]
Nevermind about grep. I see you did an exact match.

Also, this was a good catch! https://github.com/aaronkjones/rpi-k8s-node-prep/commit/e069abc0889ff9adbedeced7ef72599d6d342360 I thought it was strange that I didn't get prompted when piping it to sh, but I did when `curl -O`ed it to a file and ran it. I didn't care to study it.
